version: '3'
services:
  car-advert:
    build: ./car-advert
    image: car-advert
    ports:
    - "9000:9000"
    volumes:
    - ../:/root
    links:
    - dynamodb
    depends_on:
    - "dynamodb"
    stdin_open: true
    environment:
    # Mocked Aws SDK Credentials for Local DynamoDB
    # http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Credentials_from_Environment_Variables
    - AWS_ACCESS_KEY_ID=""
    - AWS_SECRET_ACCESS_KEY=""
    # Specify dynamoDB as local
    - LOCAL_DYNAMO_DB=true
    # Specify endpoint so it points to the dynamoDB docker container:port
    - LOCAL_DYNAMO_DB_ENDPOINT=http://localhost:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3
  dynamodb:
    build: ./dynamodb
    image: dynamodb
    ports:
    - 8000:8000
    environment:
        - TABLE=${DYNAMODB_TABLE}
